name: CI
on:
  pull_request:
    branches:
      - dev
jobs:
  pull_request_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3
        with:
          ref: dev
      - name: eslint test
        run: eslint .
      - name: ts test
        if: ${{ success() }}
        run: tsc .
      - name: failure test
        if: ${{ failure() }}
        run: echo "merge fail"
