name: CI
on:
  pull_request:
jobs:
  pull_request_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2
        with:
          ref: dev
      - name: eslint test
        run: yarn eslint .
      - name: ts test
        if: ${{ success() }}
        run: yarn tsc
      - name: failure test
        if: ${{ failure() }}
        run: echo "merge fail"
